### ISSUE TITLE
Track Changes Manually

### ISSUE THREAD

**Issue by djneely** [henk-badenhorst/vue-hotjar-next#12]
In the original vue 2 implementation there was a way to track changes manually.

```
if (this.$hj) {
  this.$hj('stateChange', '/your/url/here')
}
```

Is this no longer available in this package? If it is but missing it, how might we go about doing that?

**Comment by henk-badenhorst** [comment]
Hi, I will look into this and raise a PR in the coming week to add a global variable, there was a reason why I did not do this in the early version of Vue 3 but I can not remember what the reason was exactly, it was 2 years ago. As a temporary workaround you can try and access it directly by calling `window.hj`.

**Comment by djneely** [comment]
Awesome. Thank you for the response and the work around. We'll give that a shot.

**Comment by henk-badenhorst** [comment]
I have just pushed a new version [(2.0.0)](https://github.com/henk-badenhorst/vue-hotjar-next/releases/tag/v2.0.0) that now includes the global. I have also added some documentation on how to use it [here](https://www.npmjs.com/package/vue-hotjar-next#accessing-the-hotjar-api).  Would you mind testing this change for me and letting me know if it works for you? I have only tested it with Vite and a small Vue3 project I set up and it seems to work fine.

**Comment by djneely** [comment]
Awesome. Thanks. I'll pull and update down this week and test.

**Comment by djneely** [comment]
Just a follow up on this. I finally got around to updating and testing. This seems to work as documented. Thanks.

**Comment by henk-badenhorst** [comment]
Awesome. Thanks for letting me know. 🚀
